const DEFAULT_CARD_SIZE_PX = 174;

export const SAMPLE_CARD_DATA = {
  artist: "Queen",
  title: "Bohemian Rhapsody",
  year: "1975",
  qr_url: "https://open.spotify.com/track/4u7EnebtmKWzANvKgiJJEc",
  code1: "L-01",
  code2: "R-02",
};

export const DEFAULT_DESIGN_CONFIG = {
  mode: 'card',
  token: {
    text1: "TOKEN",
    text2: "SUBTITLE",
    text1Size: 24,
    text2Size: 12,
    textColor: "#000000",
    textStrokeWidth: 1.5,
  },
  card: {
    width: DEFAULT_CARD_SIZE_PX,
    height: DEFAULT_CARD_SIZE_PX,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#000000',
    showBorder: true,
    borderOnFront: false,
    borderOnBack: true,
  },
  typography: {
    fontFamily: 'Montserrat, sans-serif',
    artistWeight: 900,
    titleWeight: 700,
    yearWeight: 900,
    artistTransform: 'uppercase',
    titleTransform: 'none',
    fontVariant: 'normal',
    artistLetterSpacing: 0.05,
    titleLetterSpacing: 0,
  },
  vinyl: {
    enabled: true,
    style: 'glitch',
    lineColor: '#A9A9A9',
    glitchGapMin: 5,
    glitchGapMax: 25,
    lineWidth: 0.8,
    glowIntensity: 0,
    ringCount: 13,
    clipMargin: 1.5,
    neon: false,
    aiBackground: '',
    showCenterLabel: true,
    soundwavePoints: 180,
    soundwaveAmplitude: 8,
    soundwaveFrequency: 30,
    equalizerBars: 50,
    equalizerMaxHeight: 15,
    sunburstLines: 50,
    gridDensity: 10,
    glitchSegments: 3,
  },
  front: {
    artistFontSize: 16,
    titleFontSize: 12,
    yearFontSize: 32, // Ez az érték már létezett, de a teljesség kedvéért itt hagyom
    artistColor: '#000000',
    titleColor: '#000000',
    yearColor: '#000000', // Ez is
    paddingX: 10,
  },
  back: {
    showArtist: true,
    showTitle: true,
    showYear: true,
    showCodes: true,
    artistFontSize: 14,
    artistColor: '#000000',
    titleFontSize: 14,
    titleColor: '#000000',
    yearFontSize: 32,
    yearColor: '#000000',
    codeFontSize: 8,
    codeRotation: 'uniform',
    artistOffsetY: 10,
    titleOffsetY: 10,
    codeOffsetX: 8,
  },
  qrCode: {
    size: 50, // Százalékos érték
    color: '#000000',
    bgColor: '#FFFFFF',
    bgTransparent: false,
    frame: true,
    frameWidth: 2,
    frameBgColor: '#FFFFFF',
    frameBorderRadius: 4,
  },
  page: {
    cardsPerPage: 20,
    autoFit: true,
    gapX: 0,
    gapY: 0,
    padding: 10,
    pageFormat: 'A4',
    mirrorBacks: true,
  }
};