const DEFAULT_CARD_SIZE_PX = 174;

export const SAMPLE_CARD_DATA = {
  artist: "Queen",
  title: "Bohemian Rhapsody",
  year: "1975",
  fact: "This song has three distinct sections: a ballad segment ending with a guitar solo, an operatic passage, and a hard rock finale.",
  qr_url: "https://open.spotify.com/track/4u7EnebtmKWzANvKgiJJEc",
  code1: "L-01",
  code2: "R-02",
};

export const DEFAULT_DESIGN_CONFIG = {
  mode: 'card',
  token: {
    text1: "TOKEN",
    text2: "SUBTITLE",
    text1Size: 24,
    text2Size: 12,
    textColor: "#000000",
    showFrame: true,
    frameGlow: 5,
    frameColor: "#00FF00",
  },
  card: {
    width: DEFAULT_CARD_SIZE_PX,
    height: DEFAULT_CARD_SIZE_PX,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#000000',
  },
  vinyl: {
    enabled: true,
    style: 'glitch',
    lineColor: '#A9A9A9',
    lineGap: 5,
    lineWidth: 0.8,
    glowIntensity: 0,
    ringCount: 13,
    clipMargin: 1.5,
    neon: false,
    aiBackground: '',
    soundwavePoints: 180,
    soundwaveAmplitude: 8,
    soundwaveFrequency: 30,
    equalizerBars: 50,
    equalizerMaxHeight: 15,
    sunburstLines: 50,
    gridDensity: 10,
  },
  front: {
    artistFontSize: 16,
    artistColor: '#000000',
    artistOffset: 5,
    titleFontSize: 14,
    titleColor: '#000000',
    titleOffset: 5,
    fontFamily: 'Montserrat, sans-serif'
  },
  back: {
    artistFontSize: 14,
    artistColor: '#000000',
    titleFontSize: 14,
    titleColor: '#000000',
    yearFontSize: 32,
    yearColor: '#000000',
    factFontSize: 11,
    factColor: '#424242',
    fontFamily: 'Montserrat, sans-serif',
    codeFontSize: 8,
    codeRotation: 'uniform',
  },
  qrCode: {
    size: 90,
    color: '#000000',
    bgColor: '#FFFFFF',
    bgTransparent: false,
    positionX: 50,
    positionY: 50,
    frame: true,
    frameWidth: 2,
    frameBgColor: '#FFFFFF',
  },
  page: {
    cardsPerPage: 20,
    autoFit: true,
    gap: 0,
    padding: 10,
    pageFormat: 'A4',
    mirrorBacks: true,
  }
};